In [1]:
import numpy as np

In [4]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
a_row=np.append(a,[[10,12,15]],axis=0)
a_row

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 12, 15]])

In [9]:
a_col=np.array([25,26,78]).reshape(3,1)
a_col

array([[25],
       [26],
       [78]])

In [11]:
b=np.append(a, a_col, axis=1)
b

array([[ 0,  1,  2, 25],
       [ 3,  4,  5, 26],
       [ 6,  7,  8, 78]])