In [1]:
import numpy as np

In [3]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
a_ins=np.insert(a,3,[13,14,15],axis=0)
a_ins

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [13, 14, 15]])

In [10]:
a_del=np.delete(a_ins,2, axis=0)
a_del

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [13, 14, 15]])