In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
b=np.linspace(1,10,5)
b

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [12]:
c=np.arange(1,10,2)
c

array([1, 3, 5, 7, 9])

In [14]:
e=np.ones([3,4])
e

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
f=np.zeros([3,4])
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
g=np.random.rand(10)
g

array([0.45963808, 0.35966928, 0.44889263, 0.20760529, 0.04201628,
       0.22870361, 0.38655362, 0.89661431, 0.9136673 , 0.01853693])

In [22]:
h=np.arange(1,10).reshape(3,3)
h

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
j=np.array([[1,2,3],[4,5,6],[8,9,5]])
j

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 5]])