# Solve linear equation using Numpy

Consider following three linear equations,

3x+y+2z=2  ......(1)

3x+2y+5z=-1 .....(2)

6x+7y+8z=3  .....(3)

convert this above equation in

[A]{X}=[B] in this form 

In [15]:
import numpy as np

In [16]:
A=np.matrix("3,1,2;3,2,5;6,7,8")
A

matrix([[3, 1, 2],
        [3, 2, 5],
        [6, 7, 8]])

In [17]:
B=np.matrix("2;-1;3")
B

matrix([[ 2],
        [-1],
        [ 3]])

In [18]:
sol=np.linalg.solve(A,B)
sol

matrix([[ 1.24242424],
        [ 0.81818182],
        [-1.27272727]])