In [1]:
import numpy as np

In [2]:
mat_1=np.arange(20).reshape(5,4)
mat_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [3]:
mat_1.shape

(5, 4)

In [4]:
mat_1.size

20

In [6]:
mat_1_tran=np.transpose(mat_1)
mat_1_tran

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [7]:
mat_1_tran.shape

(4, 5)

In [10]:
mat_2=np.arange(9).reshape(3,3)
mat_2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
mat_2.shape

(3, 3)

In [12]:
mat_2.size

9

In [14]:
det_mat_2= np.linalg.det(mat_2)
det_mat_2

0.0

In [16]:
mat_3=np.matrix("3,1,2;3,2,5;6,7,8")
mat_3

matrix([[3, 1, 2],
        [3, 2, 5],
        [6, 7, 8]])

In [18]:
det_mat_3=np.linalg.det(mat_3)
det_mat_3

-33.0

In [20]:
inv_mat_3=np.linalg.inv(mat_3)
inv_mat_3

matrix([[ 0.57575758, -0.18181818, -0.03030303],
        [-0.18181818, -0.36363636,  0.27272727],
        [-0.27272727,  0.45454545, -0.09090909]])

In [23]:
r_mat_3=np.linalg.matrix_rank(mat_3)
r_mat_3

3