In [10]:
import numpy as np

In [14]:
y=np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [15]:
y[1,1]

8

In [16]:
y[1,6]

13

In [17]:
y[3:,3:]

array([[24, 25, 26, 27],
       [31, 32, 33, 34]])

In [23]:
y[:2,:2]

array([[0, 1],
       [7, 8]])

In [27]:
y[1:,1:]

array([[ 8,  9, 10, 11, 12, 13],
       [15, 16, 17, 18, 19, 20],
       [22, 23, 24, 25, 26, 27],
       [29, 30, 31, 32, 33, 34]])

In [30]:
z=np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
z_new=np.append(z,[[10,11,12]], axis=0)
z_new

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12]])

In [37]:
z_new=np.array([10,11,12]).reshape(3,1)
z_new

array([[10],
       [11],
       [12]])

In [39]:
z_new=np.append(z,z_new, axis=1)
z_new

array([[ 0,  1,  2,  0,  1,  2, 10],
       [ 3,  4,  5,  3,  4,  5, 11],
       [ 6,  7,  8,  6,  7,  8, 12]])

In [42]:
z_ins=np.insert(z, 2,[15,14,17], axis=0)
z_ins

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [15, 14, 17],
       [ 6,  7,  8]])